image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
<<<<<<< HEAD
  - java -jar artifacts\app-ibank.jar -P:profile=test &
=======
  - java -jar ./artifacts/app-ibank.jar &
>>>>>>> c2c7728606225f82c1ba94d8825d4dbaca77f320

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true
  # запускаем тест, флаг --info позволяет выводить больше информации
